-- lvim.lsp.config.gopls.setup({
--     cmd = { "gopls" },
--     filetypes = { "go", "gomod", "gowork", "gotmpl" },
--     root_dir = lvim.lsp.config.util.root_pattern("go.work", "go.mod", ".git"),
--     settings = {
--         gopls = {
--             analyses = {
--                 unusedparams = true,
--             },
--             staticcheck = true,
-- 		completeUnimported = true,
-- 	    usePlaceholders = true,
--         },
--     },
-- })
